project:
  type: website

website:
  #title: "Andrew Schweitzer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
  
  page-footer: 
    right: "&copy; 2024, Andrew Schweitzer"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute: 
  freeze: auto



